### ISSUE TITLE
client.read() - help needed

### ISSUE THREAD

**Issue by chinezbrun** [adamcharnock/mate3#12] opened 2020-12-29 22:44 UTC
just installed new version 0.5.0 and tried to run the python script from example (short version below) :
~~~~~~~~~~~~~
from loguru import logger
import sys
import time
from mate3.api import Mate3Client

logger.remove()
logger.add(sys.stderr, level="DEBUG")

with Mate3Client("192.168.0.150") as client:
    client.read()
~~~~~~~~~~~~~~
unfortunately there are some errors, see below
[output.txt](https://github.com/adamcharnock/mate3/files/5752392/output.txt)
my system: mate3s / 2 inverters VFXR /2 controllers/FNDC

**Comment by kodonnell** [comment] 2020-12-30 06:20
Hmmm, that's unusual - that was a fail-safe that I put in basically s saying (unless I've got a bug) that you've got one device that's reporting without it's 'configuration' values. (Which all should have as far as I know.) It could be old firmware (as I think I've got all the same hardware as you, just only one controller), but I'm just guessing there. I might make a quick change to make that a warning instead (provided it doesn't break things), but I'll also tidy up the debug stuff I had which dumps all the raw modbus info so you can share that with me (if you're happy to) and I can reproduce/fix. (It currently relies on client.read() working, so obviously won't help here!) Anyway, I'll have a look in the next few hours.

**Comment by kodonnell** [comment] 2020-12-30 09:36
OK, I've

- Told it to ignore any devices with this problem, as opposed to raising an error. Can you update to 0.5.1 and see if it works?
- If it still doesn't, I've started a few troubleshooting pointers in the readme - can you have a look? Specifically check `mate3 devices` has devices you expect (maybe post here?), and if not, try `mate3 dump` and attach it here, so I can reproduce.

**Comment by chinezbrun** [comment] 2020-12-31 07:42
0.5.1 installed >> same issue

attach 1 with what i tested in CLI output format
[output.txt](https://github.com/adamcharnock/mate3/files/5756721/output.txt)
attach 2 mate3_dump.txt (json)
[mate3_dump.txt](https://github.com/adamcharnock/mate3/files/5756723/mate3_dump.txt)
attach e mate3_read.txt
[mate3_read.txt](https://github.com/adamcharnock/mate3/files/5756724/mate3_read.txt)

side comment, please have a look - doesn't matter if read or dump the output file content seems to be the same 
hope that will help

**Comment by kodonnell** [comment] 2020-12-31 08:05
OK cool, that looks like it's "working" in the sense that it's now picking things up correctly and not failing, and you're getting a nice read of values etc. This error message shows what's going on:

```
Only model (<class 'mate3.sunspec.models.SplitPhaseRadianInverterRealTimeModel'>) field reads and no config (<class 'mate3.sunspec.models.RadianInverterConfigurationModel'>) fields were read. This is undefined behaviour, so ignoring <class 'mate3.sunspec.models.SplitPhaseRadianInverterRealTimeModel'>.
```

I won't be able to debug tonight, but since you've sent me the dump file (thanks!) I'll have a look in 24 hours or so. Hopefully it's just something minor (as I don't have Radians to test on).

**Comment by kodonnell** [comment] 2021-01-01 02:59
Cool, fixed in 0.5.2 (I think!). Basically, 0.5.1 was working, aside from the warning message being faulty. This was because the Radian inverters share the same configuration model, so in your case when we said to update the values for split phase inverters (if any) then it saw configuration values and no model values, hence the message. Since it's perfectly reasonable for this to be the case, I've changed the warning logic, and you shouldn't get it in 0.5.2.

Otherwise, looks like all is well, so are you happy to close this issue? Also, are you happy for me to use your JSON dump as an integration test in the repo?

**Comment by chinezbrun** [comment] 2021-01-01 10:15
yes, no problem to use my JSON dump as an integration test.
congrats for the progress!!
Please check another one, may be is only in the python code, without complete documentation I'm not able to judge
~~~
        cc = client.devices.charge_controller.config
        volts = cc.absorb_volts
        print("Before:", volts)
        cc.absorb_volts.value = volts.value + 0.1
        print("After (before writing): ", volts)
~~~
output
~~~
Traceback (most recent call last):
  File "C:\Users\chine\AppData\Local\Programs\Thonny\lib\site-packages\thonny\backend.py", line 1164, in _execute_prepared_user_code
    exec(statements, global_vars)
  File "\\HomeCloud\system\Development\Python_Scripts\Examples\Mate3_GitHubModule\TestNewMate1.py", line 29, in <module>
    cc = client.devices.charge_controller.config
  File "C:\Users\chine\AppData\Roaming\Python\Python37\site-packages\mate3\devices.py", line 154, in charge_controller
    return self._get_single_device("charge_controller")
  File "C:\Users\chine\AppData\Roaming\Python\Python37\site-packages\mate3\devices.py", line 136, in _get_single_device
    f"Must be one, and only one, {name} device to be able to use `{name}` attribute - but there are "
RuntimeError: Must be one, and only one, charge_controller device to be able to use `charge_controller` attribute - but there are 2
~~~

> Also, are you happy for me to use your JSON dump as an integration test in the repo?

**Comment by kodonnell** [comment] 2021-01-01 10:30
No worries - since you've got multiple charge controllers, you want `charge_controllers[<your port number>]`.

Sorry, the documentation for the API at the moment is really "see the code" which isn't great and only works if you know python. However, that probably won't change for a while as it's a fair bit of word to do and maintain - unless you feel like taking it on! I suspect I'll stick to example scripts (and there is one example of multiple devices of the same type - but maybe I'll make it clearer in the comments that the example only works if you have one charge controller).

**Comment by chinezbrun** [comment] 2021-01-01 11:04
~~~
cc = client.devices.charge_controllers[3].config
~~~
man.... it works! but you really need to know the syntax or at least to understand the logic behind :)

before closing this issue, could you please check below, because matter what kind of data the output file has.  
> side comment - please have a look, it doesn't matter if read or dump the output file content seems to be the same.

**Comment by kodonnell** [comment] 2021-01-01 11:15
> but you really need to know the syntax or at least to understand the logic behind :)

Yup! Checking out the code, or using an IDE with Intellisense, or using a REPL with tab-completion should help on this front until documentation comes. Let me know if you've got some ideas for changing the API to make it easier to use.

> side comment - please have a look, it doesn't matter if read or dump the output file content seems to be the same.

Sorry, missed this. If you run `mate3 read -h` you'll see explanations and that the `-c` you're using in `mate3 read --host 192.168.0.150 -f text -c /home/pi/mate3_read.txt` isn't what you think - it's not the output file, but a cache file (which normally you wouldn't worry about unless you were wanting to avoid hammering your device, and in this case, it should give exactly the same result as `mate3 dump`). You can see in your first attached output that `mate3 read` did give the correct output (in stdout - i.e. the table of values). If you want to pipe it to a file, use normal piping i.e. `mate3 read --host 192.168.0.150 -f text > /home/pi/mate3_read.txt`. If you want more control, you can use the full API and write whatever output you want.

**Closed** 2021-01-01 11:15 UTC
Labels: bug

**Comment by chinezbrun** [comment] 2021-01-01 11:48
Thank you for your great work!
